<h2>Récapitulatif de la commande</h2>
<div id="displayBasket">
	<table>
		<thead>
			<th>Quantité</th>
			<th>Nom</th>
			<th>Prix Unitaire</th>
			<th>Prix Total</th>
			<th>Action</th>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>
<form action="<?=$requestUrl ?>/payment" method="POST">
	<input type="hidden" name="basketItem" id="basketItem" value="">
	<input type="submit" value="Payer ma commande">
</form>