<!-- Message de notification -->

<!-- Code HTML à écrire -->
<?php if(array_key_exists('user', $_SESSION)) {?>
        <h1>Heureux de te revoir sur Beer4You <?=$_SESSION['user']['firstname']?></h1>
<?php } else {?>
		<h1>Bienvenu sur Beer4you</h1>
<?php } ?>

<!-- Liste des aliments -->
<p>Le site de vente de bière le plus côté du marché du poivrot, ici vous trouverez les meilleures bières, 
de la 86 à la kronembourg</p>

