<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/payment.css">
<h3>Paiement de votre commande</h3>
<div class="container">
	<form action="charge.php" method="post" id="payment-form" class="p-form">
		<div class="form-row">
			   
			    <div id="card-element" class="form-control ">
			      <!-- A Stripe Element will be inserted here. -->
			    </div>

			    <!-- Used to display form errors. -->
			    <div id="card-errors" role="alert"></div>
			  </div>

			  <button>Submit Payment</button>
	</form>
</div>
<script src="https://js.stripe.com/v3/"></script>
<script src="<?=$wwwUrl?>/js/charge.js"></script>		