<link rel="stylesheet" type="text/css" href="<?=$wwwUrl?>/css/profil.css">


<div>
	<h3>Mon Profil</h3>
	<?php if(empty($user) == false) { ?>
	<form class="b-form" action="<?=$requestUrl?>/user/profil" method="POST">
		<input type="text" name="firstname" placeholder="Prénom" value="<?=$user['firstName']?>">
		<input type="text" name="lastname" placeholder="Nom" value="<?=$user['lastName']?>">
		<input type="text" name="email" placeholder="email" value="<?=$user['email']?>">
		<input type="text" name="address" placeholder="Adresse" value="<?=$user['address']?>">
		<input type="text" name="city" placeholder="Ville" value="<?=$user['city']?>">
		<input type="text" name="zip" placeholder="Code postal" value="<?=$user['zip']?>">
		<input type="submit" value="Modifier">
	</form>
	<?php } ?>
</div>

<hr/>

<h4>Récapitulatif des commandes</h4>
<p>Cliquez sur un numéro de commande pour voir le détail !</p>
<table class="t-order">
	<thead>
		<th>Numéro de commande</th>
		<th>Prix total</th>
		<th>Date de la commande</th>
	</thead>
	<tbody>
		<?php foreach ($orders as $order): ?>
			<tr>
				<td class="link"><a href="<?=$requestUrl ?>/user/profil/detail?id=<?=$order['id']?>"><?=$order['id']?></a></td>
				<td><?=number_format($order['totalAmount'], 2)?> €</td>
				<td><?=$order['CreationTimestamp']?></td>
			</tr>
		<?php endforeach ?>
	</tbody>
</table>
