<?php if(empty($beer)== false)  { ?>

	<form action="<?= $requestUrl ?>/admin/product/update" method="POST" enctype="multipart/form-data">
		<input type="text" name="name" placeholder="Nom du produit" value="<?=$beer['Name']?>">
		<img src="<?= $wwwUrl ?>/images/beers/<?=$beer['Photo']?>">
		<input type="file" name="beer_pict">
		<textarea type="text" name="description" ><?=$beer['Description']?>
		</textarea>
		<input type="text" name="quantity" placeholder="Quantité"  value="<?=$beer['QuantityInStock']?>">
		<input type="text" name="buyPrice" placeholder="Prix de d'achat"  value="<?=$beer['BuyPrice']?>">
		<input type="text" name="salePrice" placeholder="Prix de vente"  value="<?=$beer['SalePrice']?>">
		<input type="hidden" name="beerId" value="<?=$_GET['id']?>">
		<input type="submit" name="Enregister">
	</form>

<?php } ?>