<?php if(empty($beer)== false)  { ?>
<h3>Modifiez votre bière !</h3>

<a class="comeBack"  href="<?= $requestUrl ?>/admin"><i class="fas fa-arrow-circle-left"></i></a>
	<form class="b-form" action="<?= $requestUrl ?>/admin/product/update" method="POST" enctype="multipart/form-data">
		<input type="text" name="name" placeholder="Nom du produit" value="<?=$beer['Name']?>">
		<img src="<?= $wwwUrl ?>/images/beers/<?=$beer['Photo']?>">
		<input type="file" name="beer_pict" id="beer_pict">
		<textarea type="text" name="description" ><?=$beer['Description']?>
		</textarea>
		<label>Quantité</label>
		<input type="text" name="quantity" placeholder="Quantité"  value="<?=$beer['QuantityInStock']?>">
		<label>Prix d'achat (€)</label>
		<input type="text" name="buyPrice" placeholder="Prix de d'achat"  value="<?=number_format($beer['BuyPrice'],2)?>">
		<label>Prix de vente (€)</label>
		<input type="text" name="salePrice" placeholder="Prix de vente"  value="<?=number_format($beer['SalePrice'], 2)?>">
		<input type="hidden" name="beerId" value="<?=$_GET['id']?>">
		<input type="submit" name="Enregister">
	</form>

<?php } ?>