<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/admin.css">

<h3>Admin</h3>
<div>	
	<hr/>
	<h4>Gestion des bières !</h4>
	<a class="addBeer" href="<?=$requestUrl ?>/admin/product/add"><i class="fas fa-plus-circle"></i> Ajouter une nouvelle bière</a>
	<table class="tableBeer">
		<tr class="titleBeer">	
			<td>Photo</td>
			<td>Nom</td>
			<td>Action</td>
		</tr>

		<?php foreach($beers as $beer) {?>

			<tr>	
				<td class="pBeer"><img src="<?= $wwwUrl ?>/images/beers/<?=$beer['Photo']?>"></td>
				<td class="nBeer"><?= $beer['Name'] ?></td>
				<td class="aBeer">
					<a href="<?=$requestUrl ?>/admin/product/update?id=<?=$beer['Id']?>"><i class="fas fa-pen"></i></a>
					<a href="<?=$requestUrl ?>/admin/product/delete?id=<?=$beer['Id']?>"><i class="fas fa-trash-alt"></i></a>
				</td>
			</tr>

		<?php } ?>

		</table>

		<hr/>
		<h4>Gestion des utilisateurs !</h4>

		<table class="userTable">

			<tr>	
				<td>Nom</td>
				<td>Prénom</td>
				<td>Email</td>
				<td>Role</td>
				<td>Action</td>
			</tr>

			<?php foreach($users as $user) {?>
				<?php if($user['email'] != $_SESSION['user']['email']) { ?>
				<tr>	
					<td><?=$user['lastName']?></td>
					<td><?=$user['firstName']?></td>
					<td><?=$user['email']?></td>
					<td>
						<select class="userRole" data-id="<?=$user['Id']?>">
						<?php if($user['role'] == 'user') {?>
							<option value="user" selected="">user</option>
							<option value="admin">admin</option>
						<?php } else {?>
							<option value="admin" selected>admin</option>
							<option value="user">user</option>
						<?php } ?>
						</select>
					</td>
					<td>
						<a href="<?=$requestUrl ?>/admin/user/delete?id=<?=$user['Id']?>"><i class="fas fa-trash-alt"></i></a>
					</td>
				</tr>
				<?php } ?>
			<?php } ?>

		</table>

		<hr/>
		<h4>Gestion des commandes !</h4>
		<a class="addBeer" href="<?=$requestUrl ?>/admin/order"><i class="fas fa-plus-circle"></i> Gestion des commandes</a>
</div>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/admin.js"></script>